package hanghae.ecommerce.infrastructure.fake;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

import hanghae.ecommerce.order.dao.OrderRepository;
import hanghae.ecommerce.order.domain.Order;

public class FakeOrderRepository implements OrderRepository {

	private Long autoGeneratedId = 0L;
	private final List<Order> data = new ArrayList<>();

	@Override
	public Order create(Order order) {
		Order newOrder = Order.of(++autoGeneratedId, order.getOrderItems());
		data.add(newOrder);
		return newOrder;
	}

	@Override
	public Order update(Order order) {
		data.removeIf(item -> Objects.equals(item.getId(), order.getId()));
		data.add(order);
		return order;
	}

	@Override
	public Optional<Order> findById(Long orderId) {
		return data.stream().filter(item -> Objects.equals(item.getId(), orderId)).findAny();
	}

	public void clear() {
		data.clear();
		autoGeneratedId = 0L;
	}
}
