permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      # 깃헙 Repository 코드 내려받기
      - name: Checkout
        uses: actions/checkout@v4

      # JAVA 세팅
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      # Gradle 캐싱
      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # gradlew 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Lint 체크
      - name: Check Style Main
        run: ./gradlew clean checkstyleMain
      - name: Check Style Test
        run: ./gradlew clean checkstyleTest

      # 테스트
      - name: Test Build with Gradle
        run: ./gradlew test

      # 테스트 결과 업로드
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/test

      # PR 코멘트에 테스트 결과 등록
      - name: Include test coverage report in PR comments
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: '**/build/reports/test/TEST-*.xml'

      # 프로젝트 빌드
      - name: Build with Gradle
        shell: bash
        run: ./gradlew build
